### ISSUE TITLE
to use it as decoder

### ISSUE THREAD

**Issue by nimrp01** [philipschoemig/BER-TLV#16]
Could you please guide me or provide any documentation to use this to decode BER TLV file.
The file is in binary format. When read as binary file, the sample output for the binary data file is as follow:
b'0\x82*\xd1\xa0\x10\x80\t\x18\x11 \x1807+\x05\x00\x81\x01\x00\xa2\x00\xa1\x82*\x8e\xa0\x82\x01\x8e\x80\x01\

Thanks for support

**Comment by philipschoemig** [comment]
Hi @nimrp01,
sorry, I didn't see your issue earlier.

If you want to use this library, you need to install poetry, see https://python-poetry.org/docs/#installation

Afterwards, you can install it in the local virtual environment with `poetry install` and then execute the CLI with `poetry run bertlv`.
If instead you want to use it in your own Python code, you can import the package _bertlv_ and use the method `bertlv.tree_from_binary` (see https://philipschoemig.github.io/BER-TLV/reference/bertlv.html).

Does this answer your question?
